"""empty message

Revision ID: 2a19fc56ec58
Revises: 706e9a7898e2
Create Date: 2016-02-25 00:58:18.659852

"""

# revision identifiers, used by Alembic.
revision = '2a19fc56ec58'
down_revision = '706e9a7898e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    ### end Alembic commands ###
