"""empty message

Revision ID: aa8ca64c2042
Revises: 2a19fc56ec58
Create Date: 2016-02-25 22:17:07.693667

"""

# revision identifiers, used by Alembic.
revision = 'aa8ca64c2042'
down_revision = '2a19fc56ec58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
