"""empty message

Revision ID: b48aa58e1e02
Revises: 1c7e7c88bbb0
Create Date: 2016-02-29 00:10:23.808105

"""

# revision identifiers, used by Alembic.
revision = 'b48aa58e1e02'
down_revision = '1c7e7c88bbb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    ### end Alembic commands ###
